version: '3.8'

services:
  backend:
    image: 869388145954.dkr.ecr.ap-southeast-1.amazonaws.com/dc-backend/dc1:latest
    container_name: backend
    ports:
      - "3002:3000"
    networks:
      - app-network

  frontend:
    image: 869388145954.dkr.ecr.ap-southeast-1.amazonaws.com/dc-frontend/dc1:latest
    container_name: frontend
    ports:
      - "8082:80"
    networks:
      - app-network

networks:
  app-network:
    driver: bridg