version: '3.8'

services:
  backend:
    image: 869388145954.dkr.ecr.ap-southeast-1.amazonaws.com/bb-backend/bb1:latest
    container_name: backend
    ports:
      - "3001:3000"
    networks:
      - app-network

  frontend:
    image: 869388145954.dkr.ecr.ap-southeast-1.amazonaws.com/bb-frontend/bb1:latest
    container_name: frontend
    ports:
      - "8081:80"
    networks:
      - app-network

networks:
  app-network:
    driver: bridg